<a href="https://colab.research.google.com/github/ZulKM/Task-Colledge/blob/main/Data_Preprosesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [108]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [109]:
print(x)

[['Kejaksaan' 2.0 44.0 72000.0 25000.0]
 ['Dosen' 1.0 27.0 48000.0 32000.0]
 ['Masinis' 3.0 30.0 54000.0 45000.0]
 ['Kejaksaan' 4.0 38.0 61000.0 10000.0]
 ['Pengacara' 4.0 40.0 nan 70000.0]
 ['Dosen' 1.0 35.0 58000.0 29500.0]
 ['Masinis' 2.0 nan 52000.0 13000.0]
 ['Kejaksaan' 2.0 48.0 79000.0 50000.0]
 ['Pengacara' 2.0 50.0 83000.0 59000.0]
 ['Masinis' 2.0 37.0 67000.0 45000.0]
 ['Pengacara' 2.0 30.0 58000.0 10000.0]
 ['Masinis' 3.0 31.0 52000.0 45000.0]
 ['Dosen' 4.0 54.0 79000.0 10000.0]
 ['Masinis' 4.0 nan 83000.0 70000.0]
 ['Kejaksaan' 3.0 19.0 67000.0 29500.0]
 ['Pengacara' 2.0 21.0 58000.0 13000.0]
 ['Pengacara' nan 31.0 52000.0 nan]
 ['Kejaksaan' nan 33.0 79000.0 50000.0]
 ['Masinis' 3.0 39.0 83000.0 59000.0]
 ['Dosen' 1.0 30.0 67000.0 45000.0]
 ['Dosen' nan 40.0 52000.0 10000.0]
 ['Kejaksaan' 3.0 47.0 83000.0 45000.0]
 ['Pengacara' 2.0 29.0 67000.0 nan]
 ['Pengacara' 2.0 nan 83000.0 nan]
 ['Masinis' 1.0 44.0 67000.0 50000.0]
 ['Pengacara' 1.0 32.0 58000.0 59000.0]
 ['Pengacara'

In [110]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit (x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [111]:
print(x)

[['Kejaksaan' 2.0 44.0 72000.0 25000.0]
 ['Dosen' 1.0 27.0 48000.0 32000.0]
 ['Masinis' 3.0 30.0 54000.0 45000.0]
 ['Kejaksaan' 4.0 38.0 61000.0 10000.0]
 ['Pengacara' 4.0 40.0 nan 70000.0]
 ['Dosen' 1.0 35.0 58000.0 29500.0]
 ['Masinis' 2.0 35.15384615384615 52000.0 13000.0]
 ['Kejaksaan' 2.0 48.0 79000.0 50000.0]
 ['Pengacara' 2.0 50.0 83000.0 59000.0]
 ['Masinis' 2.0 37.0 67000.0 45000.0]
 ['Pengacara' 2.0 30.0 58000.0 10000.0]
 ['Masinis' 3.0 31.0 52000.0 45000.0]
 ['Dosen' 4.0 54.0 79000.0 10000.0]
 ['Masinis' 4.0 35.15384615384615 83000.0 70000.0]
 ['Kejaksaan' 3.0 19.0 67000.0 29500.0]
 ['Pengacara' 2.0 21.0 58000.0 13000.0]
 ['Pengacara' 2.24 31.0 52000.0 nan]
 ['Kejaksaan' 2.24 33.0 79000.0 50000.0]
 ['Masinis' 3.0 39.0 83000.0 59000.0]
 ['Dosen' 1.0 30.0 67000.0 45000.0]
 ['Dosen' 2.24 40.0 52000.0 10000.0]
 ['Kejaksaan' 3.0 47.0 83000.0 45000.0]
 ['Pengacara' 2.0 29.0 67000.0 nan]
 ['Pengacara' 2.0 35.15384615384615 83000.0 nan]
 ['Masinis' 1.0 44.0 67000.0 50000.0]
 ['Penga

In [112]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [113]:
print(x)

[[0.0 1.0 0.0 0.0 2.0 44.0 72000.0 25000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0 32000.0]
 [0.0 0.0 1.0 0.0 3.0 30.0 54000.0 45000.0]
 [0.0 1.0 0.0 0.0 4.0 38.0 61000.0 10000.0]
 [0.0 0.0 0.0 1.0 4.0 40.0 nan 70000.0]
 [1.0 0.0 0.0 0.0 1.0 35.0 58000.0 29500.0]
 [0.0 0.0 1.0 0.0 2.0 35.15384615384615 52000.0 13000.0]
 [0.0 1.0 0.0 0.0 2.0 48.0 79000.0 50000.0]
 [0.0 0.0 0.0 1.0 2.0 50.0 83000.0 59000.0]
 [0.0 0.0 1.0 0.0 2.0 37.0 67000.0 45000.0]
 [0.0 0.0 0.0 1.0 2.0 30.0 58000.0 10000.0]
 [0.0 0.0 1.0 0.0 3.0 31.0 52000.0 45000.0]
 [1.0 0.0 0.0 0.0 4.0 54.0 79000.0 10000.0]
 [0.0 0.0 1.0 0.0 4.0 35.15384615384615 83000.0 70000.0]
 [0.0 1.0 0.0 0.0 3.0 19.0 67000.0 29500.0]
 [0.0 0.0 0.0 1.0 2.0 21.0 58000.0 13000.0]
 [0.0 0.0 0.0 1.0 2.24 31.0 52000.0 nan]
 [0.0 1.0 0.0 0.0 2.24 33.0 79000.0 50000.0]
 [0.0 0.0 1.0 0.0 3.0 39.0 83000.0 59000.0]
 [1.0 0.0 0.0 0.0 1.0 30.0 67000.0 45000.0]
 [1.0 0.0 0.0 0.0 2.24 40.0 52000.0 10000.0]
 [0.0 1.0 0.0 0.0 3.0 47.0 83000.0 45000.0]
 [0.0 0.0 0

In [114]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform (y)

In [115]:
print (y)

[0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1]


In [116]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [117]:
print(x_train)

[[0.0 1.0 0.0 0.0 4.0 38.0 61000.0 10000.0]
 [0.0 0.0 0.0 1.0 2.0 30.0 58000.0 10000.0]
 [0.0 0.0 0.0 1.0 2.0 35.15384615384615 83000.0 nan]
 [0.0 0.0 0.0 1.0 2.0 29.0 67000.0 nan]
 [0.0 0.0 0.0 1.0 4.0 40.0 nan 70000.0]
 [0.0 0.0 1.0 0.0 3.0 30.0 54000.0 45000.0]
 [0.0 0.0 1.0 0.0 1.0 44.0 67000.0 50000.0]
 [0.0 0.0 1.0 0.0 2.0 35.15384615384615 52000.0 13000.0]
 [0.0 1.0 0.0 0.0 2.24 33.0 79000.0 50000.0]
 [0.0 0.0 1.0 0.0 4.0 35.15384615384615 83000.0 70000.0]
 [0.0 1.0 0.0 0.0 2.0 48.0 79000.0 50000.0]
 [0.0 0.0 0.0 1.0 1.0 42.0 52000.0 45000.0]
 [1.0 0.0 0.0 0.0 1.0 27.0 48000.0 32000.0]
 [0.0 0.0 0.0 1.0 2.24 31.0 52000.0 nan]
 [0.0 1.0 0.0 0.0 2.0 44.0 72000.0 25000.0]
 [0.0 0.0 0.0 1.0 2.0 21.0 58000.0 13000.0]
 [1.0 0.0 0.0 0.0 1.0 21.0 83000.0 45000.0]
 [0.0 1.0 0.0 0.0 2.24 22.0 79000.0 10000.0]
 [0.0 0.0 1.0 0.0 2.0 37.0 67000.0 45000.0]
 [0.0 0.0 0.0 1.0 2.0 50.0 83000.0 59000.0]
 [1.0 0.0 0.0 0.0 4.0 54.0 79000.0 10000.0]
 [0.0 0.0 1.0 0.0 3.0 31.0 52000.0 45000.0]
 [1.0 

In [118]:
print(x_test)

[[0.0 1.0 0.0 0.0 3.0 19.0 67000.0 29500.0]
 [0.0 1.0 0.0 0.0 3.0 47.0 83000.0 45000.0]
 [0.0 0.0 1.0 0.0 3.0 39.0 83000.0 59000.0]
 [1.0 0.0 0.0 0.0 2.24 40.0 52000.0 10000.0]
 [0.0 0.0 0.0 1.0 1.0 32.0 58000.0 59000.0]
 [1.0 0.0 0.0 0.0 1.0 30.0 67000.0 45000.0]]


In [119]:
print(y_train)

[0 1 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1]


In [120]:
print(y_test)

[1 0 0 1 0 0]


In [121]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [122]:
print (x_train)

[[0.0 1.0 0.0 -0.7302967433402215 1.8009153873319668 0.3068536010295999
  -0.4580544452229382 -1.3353195353595355]
 [0.0 0.0 0.0 1.3693063937629153 -0.2557407153808058 -0.6106386660489044
  -0.7018576176803087 -1.3353195353595355]
 [0.0 0.0 0.0 1.3693063937629153 -0.2557407153808058
  -0.019561917065637275 1.3298354861311121 nan]
 [0.0 0.0 0.0 1.3693063937629153 -0.2557407153808058 -0.7253251994337174
  0.02955189969180281 nan]
 [0.0 0.0 0.0 1.3693063937629153 1.8009153873319668 0.536226667799226 nan
  1.7081437930952463]
 [0.0 0.0 1.0 -0.7302967433402215 0.7725873359755805 -0.6106386660489044
  -1.026928514290136 0.4400340729057539]
 [0.0 0.0 1.0 -0.7302967433402215 -1.284068766737192 0.9949728013384782
  0.02955189969180281 0.6936560169436524]
 [0.0 0.0 1.0 -0.7302967433402215 -0.2557407153808058
  -0.019561917065637275 -1.1894639625950498 -1.1831463689367965]
 [0.0 1.0 0.0 -0.7302967433402215 -0.008941983055272872
  -0.2665790658944653 1.004764589521285 0.6936560169436524]
 [0.0 0.0

In [123]:
print (x_test)

[[0.0 1.0 0.0 -0.7302967433402215 0.7725873359755805 -1.8721905332818478
  0.02955189969180281 -0.34619395361173144]
 [0.0 1.0 0.0 -0.7302967433402215 0.7725873359755805 1.3390324014929174
  1.3298354861311121 0.4400340729057539]
 [0.0 0.0 1.0 -0.7302967433402215 0.7725873359755805 0.42154013441441296
  1.3298354861311121 1.1501755162118696]
 [1.0 0.0 0.0 -0.7302967433402215 -0.008941983055272872 0.536226667799226
  -1.1894639625950498 -1.3353195353595355]
 [0.0 0.0 0.0 1.3693063937629153 -1.284068766737192 -0.38126559927927833
  -0.7018576176803087 1.1501755162118696]
 [1.0 0.0 0.0 -0.7302967433402215 -1.284068766737192 -0.6106386660489044
  0.02955189969180281 0.4400340729057539]]
